name: 'Issue Template Parser'
description: 'Use this action to convert issues into a unified JSON structure'
branding:
  icon: "check-square"
  color: green
inputs:
  body:
    description: 'The RAW body of the issue to parse if you want to override the default'
outputs:
  json:
    description: 'JSON string'
runs:
  using: 'node12'
  main: 'dist/index.js'
